### ISSUE TITLE
[Suggestion]: Add token to checkout step

### ISSUE THREAD

**Issue by mbruno-kr** [mbround18/auto#1]
Ran into an issue with 403's and had to add the token to the checkout step: 

```yaml
name: Release
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with: 
        depth: 0 # <- Suggested to get all tags
        token: ${{ secrets.GH_TOKEN }} # <- This seems to be required

     - name: release
       env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
       uses: mbround18/auto@v1.0.0
```
